title: "Axiom Cortex™"
author: "TeamStation AI"
description: "Technical Methodology & Documentation"
baseurl: "" # Do not change for user/org site
url: "https://teamstationai.github.io"
theme: moonwalk-jekyll-theme

logo: /assets/axiom-logo.png # Place your logo here

color_scheme: dark

# Custom colors (edit as needed for your brand)
colors:
  primary: "#7bb3ff"
  background: "#161b22"
  accent: "#7bb3ff"
  muted: "#a6adbb"
  header: "#0d1117"
